package lgl.bayern.de.ecertby.model.util;

public enum EmailNotificationType {
    CERTIFICATE_ASSIGNED,
    CERTIFICATE_COMPANY_GENERAL,
    CERTIFICATE_COMPANY_TEAM,
    CERTIFICATE_COMPANY_USER,
    CERTIFICATE_FORWARDED,
    CERTIFICATE_COMPLETE_FORWARDED,
    FEATUREBOARD_ENTRY_ADDED
}
